language: java
sudo: required
services: docker
install: true
jdk:
- oraclejdk8
script:
- mvn clean install
- docker build -t jmstool-webspheremq -f docker/tomcat-websphereMQ/Dockerfile .
- docker build -t jmstool-activemq -f docker/tomcat-activeMQ/Dockerfile .
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" 
- docker tag jmstool-webspheremq:latest $DOCKER_USER/jmstool-webspheremq:latest
- docker push $DOCKER_USER/jmstool-webspheremq
- docker tag jmstool-activemq:latest $DOCKER_USER/jmstool-activemq:latest
- docker push $DOCKER_USER/jmstool-activemq
env:
  global:
  - secure: HJ67PfWPLD48QZeRgq12GFGM3Ti9cqIBVO8Eu7Q5YVSZLI7Eyn+Ip8r8fP5CtT6Z+jeZRlgG3fWWIpsnWgMdylkjVM/y/FhSofFb7EN+zXGawyFMeokN1hHKasC5iyURZ8V1DchzTExf8/vgIjvvnSc5NakwFZjPc0d4dLXn8DdZtCDLTYysB5FTtCB52B64xDz66SOYE4MAjKd+jtX34Ca47ywRvkUyVcb6vHkXlTrtwdfbLo/hhS8HP9REPzAF48JX31WO2asauxL/lSL16eCyc4c5vREliCMTZT1yoN23/tisw9j43pOoTrrdTBo0A843gEIyHMczlT8mEV6UxuG8cql0OUnSfYomoAnsFlx281Hrn4tjU/q+k9SeKcjnER7jO20JDx8ekk+40pPfbOHopslSvgQCwCVj0Q5/tOQlsiAFqKpcCIA9MJZXozzFkrBbIQ8HppyyOjxP03qeRJPUzYblrCeLyrDC+LWhhNqgmZQPX3cLucDrDh5FMLpCf/lX+auSj2LuTXeQt6nJipx6qAcFGcgHjlC/hSWZkZ6XHnYat8A48tFRx2NJQsYnZ3b2nys10Yd3KfUg624G2Za5Y/Y0oPnTDBzzfs6cPlddgp50cqYxZRQONkdUR6FTJVLtgPU6jKzBnSuN+KOv7+bngzVQrvVxMq37U4pcbZ8=
  - secure: bCgsfYeKkDT12ZaaqW1YaDWjMJw80FzeHUpSVyHTlvIH1IUmILPScjFRUDQvKIp2scfRiTKWqEUTFmfjOLslRLt4hdGA/1xs3l6iDk0z/rNOQx5DNgj9hjym0m3ASXp570TFOS7D45FpA8RVwf/INuwPCbiCPZf+0F92zgNC8kPCpRWOdanZmxDchdvV3O8EW/KUmuF+40vy5A/NlPPwU/MsQ+jT4odEsvIiLb4gk+2S+mPp7Q9HE52fs8dbXCJLCMvqrbivBts7JGCe2ZBhDd60IhaNAWlfXkWUF9LsU4cglse1hDfuJ3amS2wf4yMRhqoa6LdvrBflUYEcKTbNsV6GrufEbOND4mgyMn4XUSdj5qQqJZ4Zl/2iI8uZ5D7bRDBKk5/+o1+dOFEkgK6Lx3ZgXLdDluyUw/kY20fTAqI2DpDfhWU2dHlfPElnjtvqG53sKv78l8YrdkuaXKYfbGYVwYh4V8zpSX9PYIFDNYjg99UnTf1HEpDkd7jpfjKe94KcBdFus41+VFCp/ieOF3IoOx+Hf65i3uzYjVxdSCkb83opTah1/ep1PYzOM3CB9/OT1tSaGen8iFBEGVDwC+tUJIHNUKIJpttL7PksuXTD2tzvzRSF+u+IVwpzwOVWcrwZSJBcNkp0ryBxunNr5x0i90ixcByxZxeY2t75rvU=
