language: java
sudo: required
services: docker
install: true
dist: trusty
jdk:
- oraclejdk8
script:
- mvn clean install
- docker build -t jmstool-webspheremq -f docker/tomcat-websphereMQ/Dockerfile .
- docker build -t jmstool-activemq -f docker/tomcat-activeMQ/Dockerfile .
- docker build -t jmstool-artemismq -f docker/tomcat-artemisMQ/Dockerfile .
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" 
- docker tag jmstool-webspheremq:latest $DOCKER_USER/jmstool-webspheremq:latest
- docker push $DOCKER_USER/jmstool-webspheremq
- docker tag jmstool-activemq:latest $DOCKER_USER/jmstool-activemq:latest
- docker push $DOCKER_USER/jmstool-activemq
- docker tag jmstool-artemismq:latest $DOCKER_USER/jmstool-artemismq:latest
- docker push $DOCKER_USER/jmstool-artemismq
