version: '2'
services:
  tomcat:
    image: spx01/jmstool-activemq
    container_name: jmstool-tomcat
    ports:
     - "8080:8080"
    environment:
     - TZ=Europe/Berlin
     - spring.jms.jndi-name=java:comp/env/jms/QCF
     - jmstool.incomingQueues=java:comp/env/jms/QDEV1
     - jmstool.outgoingQueues=java:comp/env/jms/QDEV2
    volumes:
    - ./context.xml:/usr/local/tomcat/conf/context.xml
  activeMQ:
    image: webcenter/activemq
    container_name: jmstool-activeMQ
    environment:
      - ACTIVEMQ_STATIC_QUEUES=DEV.QUEUE.1;DEV.QUEUE.2
    ports:
     - "8161:8161"
